### ISSUE TITLE
segfault when running calamares

### ISSUE THREAD

**Issue by edwardando** [artix-linux/calamares#2]
Was trying an install on a Mac Book Pro 11,1 and got repeated segfaults when launching:
The first screen of the GUI shows up and then disappears systematically.

If one is fast enough to click next twice, sometimes the program does not crash...

This also happens in Manjaro OpenRC with me.

**Comment by udeved** [comment]
https://github.com/artix-linux/netgroups/commit/2a52a13bdd725a04f9633cfb3a0c8cd5ac3affbe

Should be fixed on artix, for manjaro please go to manjaro issue tracker.
