### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by udeved** [artix-linux/calamares#4]
Files we need to package, formerly written by buildiso. @DamnWidget 

- [x] settings.conf
- [x] machineid.conf
- [x] finished.conf
- [x] displaymanager.conf
- [x] welcome.conf
- [x] umount.conf
- [x] locale.conf

See this [commit](https://github.com/artix-linux/artools/commit/902a3913c857b32dc70ca2789c68bea5afc26f91) in artools

and files in calamares
https://github.com/artix-linux/calamares/tree/artix/data/artix/modules

The files should be packaged in /usr/share/calamares/ where all other module conf resides.

**Comment by DamnWidget** [comment]
We can close this right?

**Comment by udeved** [comment]
Yep :)
